# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='publisher',
        ),
        migrations.AddField(
            model_name='author',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Publisher'),
        ),
    ]
