# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171018_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='publisher',
        ),
    ]
