# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_author_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='icon',
            field=models.ImageField(blank=True, default=-1, upload_to='', verbose_name='Thumbnail'),
            preserve_default=False,
        ),
    ]
