# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171018_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Thumbnail'),
        ),
    ]
